_target_: pytorch_lightning.Trainer

#gpu: 1
accelerator: "gpu"
devices: 1
precision: 16

min_epochs: 1
max_epochs: 100

gradient_clip_val: 1.0


# number of validation steps to execute at the beginning of the training
num_sanity_val_steps: 0