[tool.poetry]
name = "emulator"
version = "0.1.0"
description = "ClimateSet Emulator"
authors = ["liellnima <julia.kaltenborn@mail.mcgill.ca>"]
license = "AGPL-3.0-or-later"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9"
xarray = "2024.7.0"
torch = "2.2.2"
dask = "2024.8.0"
wandb = "0.17.8"
hydra-core = "1.3.2"
segmentation-models-pytorch = "0.3.4"
netcdf4 = "1.7.1.post2"
pytorch-lightning = "2.2.3"
gpytorch = "1.12"
codecarbon = "2.6.0"
torch-tb-profiler = "0.4.3"
torchvision = "0.17.2"
numpy = "1.26.4"


[tool.poetry.group.dev.dependencies]
pytest = "^8.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
