tensorboard:
  _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  save_dir: "${work_dir}/tensorboard/"
  name:  ${name}
  log_graph: False
  default_hp_metric: True
  prefix: ""
  # version: ""