name: ssp package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    # - name: Install system dependencies (attention! different OS)
    #   run: |
    #     sudo apt-get install [...]
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Setup environment 
      run: |
        bash setup.sh
    - name: Download data 
      run: |
        bash setup.sh -d
    - name: Test if you can run one single model
      run: |
        source env_emulator/bin/activate
        python emulator/run.py experiment=github_workflow.yaml
    - name: Test metrics and losses
      run: |
        cd tests
        pytest
    # - name: Pipx build
    # - name: check dist
    # - name: publish dist (on TestPyPi)